version: "3.9"

volumes:
  tosca-geoserver-dev-1:
  geo-db-data-dev:

services:
  db:
    image: kartoza/postgis:${POSTGIS_VERSION_TAG}
    container_name: tosca-2-db-dev
    volumes:
      - geo-db-data-dev:/var/lib/postgresql
    ports:
      - ${POSTGRES_PORT}:5432
    environment:
      - POSTGRES_DB=${POSTGRES_DB}
      - POSTGRES_USER=${POSTGRES_USER}
      - POSTGRES_PASS=${POSTGRES_PASS}
      - ALLOW_IP_RANGE=${ALLOW_IP_RANGE}
      - FORCE_SSL=TRUE
    restart: on-failure
    healthcheck:
      test: "PGPASSWORD=${POSTGRES_PASS} pg_isready -h 127.0.0.1 -U ${POSTGRES_USER} -d ${POSTGRES_DB}"

  geoserver:
    build: ./geoserver
    image: tosca-geoserver-dev
    container_name: tosca-2-geoserver-dev-container
    volumes:
      - tosca-geoserver-dev-1:/usr/share/geoserver/data_dir
      - /home/ortak/Desktop/sandbox/tosca-geoserver-postgis-test/docker-geoserver/geo-data:/mnt/data
      - /home/ortak/Desktop/HCU/LIG/data:/mnt/LIG
    ports:
      - ${GEOSERVER_PORT}:8080
